## NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [16]:
# arr = np.array(my_list)

In [6]:
# above, we turned a list into an array

In [7]:
my_2d_list = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_2d_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# we just turned a list of lists into a 2d array!

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.linspace(0,30,45)

array([ 0.        ,  0.68181818,  1.36363636,  2.04545455,  2.72727273,
        3.40909091,  4.09090909,  4.77272727,  5.45454545,  6.13636364,
        6.81818182,  7.5       ,  8.18181818,  8.86363636,  9.54545455,
       10.22727273, 10.90909091, 11.59090909, 12.27272727, 12.95454545,
       13.63636364, 14.31818182, 15.        , 15.68181818, 16.36363636,
       17.04545455, 17.72727273, 18.40909091, 19.09090909, 19.77272727,
       20.45454545, 21.13636364, 21.81818182, 22.5       , 23.18181818,
       23.86363636, 24.54545455, 25.22727273, 25.90909091, 26.59090909,
       27.27272727, 27.95454545, 28.63636364, 29.31818182, 30.        ])

## NumPy Indexing and Selection

In [19]:
import numpy as np

In [21]:
arr = np.arange(0,11)

In [23]:
arr[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [24]:
arrr = np.arange(50).reshape(5,10)

In [25]:
arrr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [26]:
arrr[2:,:9]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28],
       [30, 31, 32, 33, 34, 35, 36, 37, 38],
       [40, 41, 42, 43, 44, 45, 46, 47, 48]])

## NumPy Operators

In [27]:
arr3 = np.arange(11)